"""Build the V2 content, theme tokens and editable examples using only Python stdlib.
Run from any directory: python3 V2/12_Developer/build-v2.py
Original logo masters are intentionally never modified.
"""
from pathlib import Path
import json, re, hashlib, csv, html, shutil

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT.parent / 'V1/extracted/Condo-Ninja-Brand'
def write(path, text):
    p = ROOT / path; p.parent.mkdir(parents=True, exist_ok=True); p.write_text(text, encoding='utf-8')
def dump(path, value): write(path, json.dumps(value, ensure_ascii=False, indent=2)+'\n')

tokens=json.loads((SOURCE/'03_Color/brand-tokens.json').read_text())
tokens.pop('$schema',None)
tokens.update(version='2.0.0', description='Tokens simples de implementação. Não declara conformidade com um schema DTCG.')
tokens['typography']['family']['brand']='"Condo Goldman", sans-serif'
tokens['theme']={
 'light':{'background':'#FAFBFD','surface':'#FFFFFF','surfaceSubtle':'#F2F5F9','text':'#050B1A','muted':'#34507F','border':'#C9D6EA','controlBorder':'#6B85AD','accent':'#0B4BB5','action':'#1B6BFF','onAction':'#FFFFFF','focus':'#0B4BB5','positive':'#166534','positiveSurface':'#DCFCE7','attention':'#854D0E','attentionSurface':'#FEF3C7','alert':'#B42318','alertSurface':'#FEE4E2','verified':'#115E59','verifiedSurface':'#CCFBF1'},
 'dark':{'background':'#050B1A','surface':'#0A1428','surfaceSubtle':'#101E3A','text':'#FAFBFD','muted':'#9AB0D0','border':'#23385F','controlBorder':'#6B85AD','accent':'#5AC8FF','action':'#5AC8FF','onAction':'#050B1A','focus':'#5AC8FF','positive':'#4ADE80','positiveSurface':'#123327','attention':'#F6C453','attentionSurface':'#302611','alert':'#FF8A7A','alertSurface':'#341C23','verified':'#2DD4BF','verifiedSurface':'#0C302E'}
}
tokens['component']={'targetMin':'44px','focusWidth':'3px','focusOffset':'4px','readingWidth':'66ch','wordmarkWeight':400,'chartLineWidth':'3px'}
tokens['motion']['reduced']={'duration':'0.01ms','iterations':1,'scrollBehavior':'auto'}
tokens['opacity']['disabled']=1
tokens['color']['semantic'].update(focusLight='#0B4BB5',focusDark='#5AC8FF',linkLight='#0B4BB5',linkDark='#74D1FF')
for folder in ['03_Color','12_Developer']:dump(folder+'/brand-tokens.json',tokens)
def kebab(s):return re.sub(r'([A-Z])',r'-\1',s).lower()
css=['/* Generated from brand-tokens.json. Theme: data-theme="light" | "dark". */',':root {']
for group in ['ink','paper','signal','functional','special','base']:
 for name,val in tokens['color'][group].items():css.append(f'  --cn-{group}-{kebab(name)}: {val};')
for group,prefix in [('spacing','space'),('radius','radius'),('shadow','shadow'),('opacity','opacity'),('gradient','gradient'),('border','border')]:
 for name,val in tokens[group].items():css.append(f'  --cn-{prefix}-{kebab(name)}: {val};')
for group,prefix in [('family','font'),('size','text'),('weight','weight'),('lineHeight','leading'),('tracking','tracking')]:
 for name,val in tokens['typography'][group].items():css.append(f'  --cn-{prefix}-{kebab(name)}: {val};')
for group,prefix in [('duration','duration'),('easing','ease')]:
 for name,val in tokens['motion'][group].items():css.append(f'  --cn-{prefix}-{name}: {val};')
for name,val in tokens['component'].items():css.append(f'  --cn-{kebab(name)}: {val};')
css.append('}')
for mode,values in tokens['theme'].items():
 css.append((':root, ' if mode=='light' else '')+f'[data-theme="{mode}"] {{')
 css.extend(f'  --cn-{kebab(name)}: {val};' for name,val in values.items());css.append('}')
css.append('@media (prefers-reduced-motion: reduce) { :root { --cn-duration-fast: 0.01ms; --cn-duration-standard: 0.01ms; --cn-duration-deliberate: 0.01ms; } }')
for folder in ['03_Color','12_Developer']:write(folder+'/variables.css','\n'.join(css)+'\n')
write('12_Developer/tailwind-brand-config.js','/** Tailwind v3 ESM extension. See README for Tailwind v4. */\nexport default '+json.dumps({'theme':{'extend':{'colors':{g:tokens['color'][g] for g in ['ink','paper','signal']},'fontFamily':{'brand':['Condo Goldman','sans-serif'],'sans':['Geist','sans-serif'],'mono':['Geist Mono','monospace']},'borderRadius':tokens['radius']}}},indent=2)+';\n')
write('12_Developer/tailwind-brand-v4.css','/* Import variables.css first, then this after your Tailwind v4 import. */\n@theme inline {\n --color-cn-background: var(--cn-background);\n --color-cn-surface: var(--cn-surface);\n --color-cn-text: var(--cn-text);\n --color-cn-accent: var(--cn-accent);\n --color-cn-action: var(--cn-action);\n --font-brand: "Condo Goldman", sans-serif;\n --font-sans: Geist, sans-serif;\n --font-mono: "Geist Mono", monospace;\n}\n')

data={'disclosure':'DADOS FICTÍCIOS PARA DEMONSTRAÇÃO. Não representam mercado ou condomínio real.','currency':'BRL','unit':'R$/elevador/mês','period':'Jan-Jun 2026','scope':'Manutenção preventiva de um elevador, sem peças ou modernização.','geography':'Recorte geográfico fictício; substituir antes de uso real.','sampleSize':12,'sampleType':'Amostra sintética, sem validade estatística','months':['Jan','Fev','Mar','Abr','Mai','Jun'],'observed':[1200,1250,1300,1450,1600,1800],'lower':[1100]*6,'upper':[1500]*6,'sources':[{'id':'DEMO-01','name':'Contrato de manutenção (fictício)','status':'disponível'},{'id':'DEMO-02','name':'Tabela de preços comparáveis (sintética)','status':'disponível'},{'id':'DEMO-03','name':'Aditivo de escopo','status':'faltante'}],'confidence':{'label':'Limitada','reason':'O aditivo não está disponível e a amostra é sintética.'},'finding':'Junho está 20% acima do limite superior ilustrativo.','formula':'(1800 / 1500 - 1) × 100 = 20%','nextStep':'Solicitar o aditivo e confirmar peças, plantões e escopo antes de comparar.'}
dump('08_Data_Visualization/examples/benchmark-demo.json',data)

def lum(h):
 a=[int(h[i:i+2],16)/255 for i in (1,3,5)];a=[v/12.92 if v<=.04045 else ((v+.055)/1.055)**2.4 for v in a];return sum(v*w for v,w in zip(a,[.2126,.7152,.0722]))
def contrast(a,b):
 x,y=sorted([lum(a),lum(b)]);return (y+.05)/(x+.05)
rows=[]
for mode,v in tokens['theme'].items():
 for fg,bg in [('text','background'),('muted','surface'),('accent','background'),('onAction','action'),('focus','background'),('positive','positiveSurface'),('attention','attentionSurface'),('alert','alertSurface'),('verified','verifiedSurface'),('controlBorder','surface')]:
  ratio=contrast(v[fg],v[bg]);threshold=3 if fg in ['focus','controlBorder'] else 4.5
  rows.append({'theme':mode,'foreground':fg,'background':bg,'foregroundHex':v[fg],'backgroundHex':v[bg],'ratio':round(ratio,3),'threshold':threshold,'pass':ratio>=threshold})
dump('03_Color/contrast-audit.json',rows)
assert all(r['pass'] for r in rows),rows

# Human-readable editorial source is shared by the book, reference HTML and QA.
pages=[]
def page(section,title,lead,items=(),kind='text',asset=None):
 pages.append(dict(section=section,title=title,lead=lead,items=[{'title':a,'body':b} for a,b in items],kind=kind,asset=asset))
page('A MARCA','Clareza para quem\npaga condomínio.','Condo Ninja\nSistema de marca 2.0\nEstratégia, identidade e decisões de produto.',kind='cover')
page('GUIA DE LEITURA','Um sistema para usar.','A marca organiza informação para devolver capacidade de decisão. Este livro conecta essa ideia a regras, exemplos e arquivos editáveis.', [('01 / Estratégia e voz','Por que existimos, para quem trabalhamos e como falamos.'),('02 / Identidade','Símbolo, palavra, cor, tipografia e composição.'),('03 / Experiência e aplicações','Dados, produto, mobilização, canais e governança.'),('04 / Implementação','Tokens, acessibilidade, controle de qualidade e decisões abertas.')],kind='index')
page('RESUMO EXECUTIVO','Uma segunda opinião\ndo lado de quem paga.','A Condo Ninja organiza documentos, contextualiza despesas e mostra quais perguntas merecem resposta.', [('Posicionamento','Inteligência condominial independente para proprietários e moradores. A tecnologia apoia a análise. O benefício é entender e decidir.'),('Promessa','Cada achado importante deve apresentar fonte, contexto, limitações e um próximo passo proporcional.'),('Expressão','Ink cria um campo de leitura calmo. Signal destaca o que importa. O olhar do símbolo comunica atenção e precisão.')])
page('CONTEXTO','Quem paga precisa\nconseguir entender.','Síndico, administradora e moradores lidam com a mesma estrutura a partir de posições diferentes.', [('Gestão','Síndico e administradora operam a gestão e produzem ou recebem documentos.'),('Proprietários e moradores','Pagam as despesas e convivem com seus efeitos. Precisam de informação compreensível para participar.'),('Papel da marca','Oferecer uma leitura independente. Respeitar atribuições formais e diferentes formas de participação, sem sugerir que todo morador possui o mesmo poder de voto.')])
page('PROBLEMA','A informação existe.\nA resposta ainda falta.','Balancetes, contratos e atas isolados não explicam, sozinhos, por que uma despesa mudou.', [('Perguntas reais','Por que a taxa aumentou? O que este contrato inclui? Quais documentos ainda faltam?'),('Custo da fragmentação','Informações em arquivos e conversas diferentes dificultam a comparação e repetem o trabalho.'),('O que entregamos','Uma leitura com contexto, evidências acessíveis e próximos passos que o morador consegue executar.')])
page('PÚBLICO','Pessoas comuns.\nPatrimônio compartilhado.','O público central são proprietários e moradores de condomínios residenciais.', [('Proprietário que quer entender','Precisa localizar o motivo de uma despesa e formular uma pergunta útil.'),('Morador que colabora','Pode fornecer documentos e contexto, dentro das permissões aplicáveis.'),('Conselho e grupo de moradores','Precisam reunir informações e coordenar decisões com responsabilidade.'),('Extensões futuras','Investidores, compradores e profissionais de apoio. A diligência pré-compra não substitui o foco atual.')])
page('INSIGHT','Entender muda\na qualidade da pergunta.','O usuário não precisa se tornar contador para reconhecer uma lacuna, pedir um documento ou comparar dois escopos.', [('Informação','Documentos e registros organizados.'),('Clareza','O que os dados permitem afirmar e o que continua incerto.'),('Coordenação','Pessoas colaborando com evidências e perguntas.'),('Decisão','Uma ação proporcional à informação disponível.')],kind='sequence')
page('DIREÇÃO','Clareza independente.','A essência reúne benefício e compromisso: tornar compreensível sem assumir o interesse de quem administra.', [('Propósito','Reequilibrar o acesso à informação nos condomínios.'),('Missão','Dar a proprietários e moradores contexto e ferramentas para entender despesas, avaliar informações e coordenar perguntas.'),('Visão','Tornar a transparência verificável uma prática comum na vida condominial.')])
page('VALORES','Compromissos que\naparecem no produto.','Valores devem orientar decisões observáveis.', [('Independência','Identificar fontes e conflitos de interesse. Não vincular conclusões a metas comerciais.'),('Evidência','Permitir rastrear uma afirmação até a fonte e distinguir o que foi apenas informado.'),('Clareza','Explicar limites com a mesma atenção dedicada aos resultados.'),('Participação responsável','Convidar para colaborar, restringindo acesso a dados pessoais e documentos privados.')])
page('PROMESSA','Informação organizada.\nDecisão mais consciente.','A marca promete um método de esclarecimento, sem garantir economia ou antecipar o resultado de uma análise.', [('Prova necessária','Fonte e período junto da afirmação. Método explícito quando existir comparação.'),('Limite assumido','Quando faltar evidência, dizer o que falta e como isso afeta a leitura.'),('Regra comercial','Nenhum pagamento muda uma conclusão ou confere um nível de governança.')])
page('POSICIONAMENTO','A segunda opinião\nindependente do condomínio.','Para proprietários e moradores que querem entender como os recursos do condomínio são utilizados, a Condo Ninja organiza documentos e contextualiza sinais para apoiar decisões com evidências.', [('Categoria','Plataforma de inteligência e análise condominial.'),('Diferencial','Independência combinada com rastreabilidade, comparação contextualizada e colaboração.'),('Razão para acreditar','O produto mostra de onde veio a informação, o que foi verificado e qual é a limitação. Funcionalidades futuras devem ser apresentadas como futuras.')])
page('PERSONALIDADE','Competência calma.','O arquétipo orientador é o Sábio, com uma atitude protetora. Não há proporções numéricas ou pontuação psicológica a comunicar.', [('Precisa','Nomeia o dado, a fonte e a unidade.'),('Curiosa','Investiga explicações alternativas antes de concluir.'),('Incisiva','Formula perguntas claras sem insinuar culpa.'),('Próxima','Usa português cotidiano e explica o termo técnico quando necessário.')])
page('VOZ','Firme no método.\nCuidadosa na conclusão.','Toda comunicação distingue registro, interpretação e decisão.', [('Dado','Registro observado: o documento informa R$ 1.800.'),('Sinal','Comparação que merece atenção: o valor excede uma referência de escopo equivalente.'),('Hipótese','Explicação a testar: o contrato pode incluir serviços adicionais.'),('Evidência e conclusão','Uma fonte sustenta ou enfraquece a hipótese. A conclusão depende do conjunto, das lacunas e da avaliação responsável.')])
page('MENSAGENS','Quatro perguntas\norganizam a narrativa.','Cada mensagem parte de uma dúvida concreta do morador.', [('Para onde vai meu dinheiro?','Organização documental e clareza financeira.'),('O que é possível comparar?','Referências com período, unidade e escopo equivalentes.'),('Em que informação posso confiar?','Fontes rastreáveis, limites e revisão.'),('O que podemos fazer agora?','Solicitar documentos, perguntar com contexto e convidar para colaborar.')])
page('MANIFESTO','Quem paga merece entender.','Todo mês, o condomínio reúne recursos de muitas pessoas. Cada decisão afeta um patrimônio compartilhado.', [('Nossa atitude','Organizar o que está disperso. Explicar o que parece complexo. Encontrar a pergunta que ainda não foi feita.'),('Nosso compromisso','Mostrar a fonte. Reconhecer a lacuna. Considerar outra explicação. Corrigir quando novas evidências mudarem a leitura.'),('Nossa ambição','Fazer a informação circular com responsabilidade, para que cada pessoa participe com mais clareza e cada decisão tenha uma base melhor.')],kind='manifesto')
page('ASSINATURAS','Clareza para quem\npaga condomínio.','Tagline principal. Une benefício, público e categoria em uma frase simples.', [('Assinatura secundária','A segunda opinião independente do seu condomínio.'),('Campanha','Seu dinheiro merece um ninja. Usar acompanhada de contexto, sem transformar a análise em espetáculo.'),('Regra de escolha','Uma assinatura por peça. A tagline não é obrigatória quando o contexto já explica o serviço.')])
copy10='Inteligência independente para moradores entenderem despesas e decidirem com clareza.'
copy30='A Condo Ninja organiza documentos e contextualiza despesas para que proprietários e moradores entendam seu condomínio, façam perguntas melhores e participem das decisões com evidências, independência e clareza no cotidiano.'
copy100='A Condo Ninja é uma plataforma independente de inteligência condominial para proprietários e moradores. Organiza documentos, contextualiza despesas e reúne evidências para ajudar quem paga condomínio a compreender as decisões que afetam seu patrimônio. Seu Raio-X apresenta informações disponíveis, sinais que merecem atenção, lacunas e próximos passos. Comparações precisam considerar período, região, unidade e escopo. A tecnologia apoia a análise, enquanto conclusões exigem avaliação responsável. A proposta inclui colaboração entre moradores, respeitando permissões e privacidade. A marca não promete economia garantida nem transforma suspeitas em acusações. Seu compromisso é devolver clareza para que cada pessoa possa perguntar e decidir melhor.'
for n,t in [(10,copy10),(30,copy30),(100,copy100)]:assert len(t.split())==n,(n,len(t.split()))
dump('01_Brand_Book/source/brand-copy.json',{'10':copy10,'30':copy30,'100':copy100})
page('DESCRIÇÕES','A mesma marca,\nem três extensões.','Textos editoriais com contagem verificada por palavras separadas por espaço.', [('10 palavras',copy10),('30 palavras',copy30),('100 palavras',copy100)],kind='copy')
page('INSTITUCIONAL','Uma apresentação\nsem promessas prematuras.','A Condo Ninja é uma plataforma independente de inteligência condominial. Organiza documentos e informações para apoiar proprietários e moradores na compreensão de despesas, na formulação de perguntas e na participação responsável.', [('Elevator pitch','Você paga condomínio, mas nem sempre consegue entender o que está por trás dos números. A Condo Ninja organiza os documentos e mostra o que merece atenção, com fonte, contexto e um próximo passo.'),('Complemento em inglês','Condo Ninja is an independent condominium intelligence platform that helps residents understand expenses, trace evidence and ask better questions.'),('Uso no MVP','Descrever apenas o que está disponível. Análise humana, benchmarking e módulos adicionais não devem aparecer como ativos se ainda estiverem em desenvolvimento.')])
page('LINGUAGEM','Uma frase pode mudar\na leitura de um achado.','Preferir informação verificável e convites à investigação.', [('Em vez de “Encontramos fraude”','“Este pagamento precisa de documentação complementar.”'),('Em vez de “Economize 30%”','“Compare escopo e condições antes de avaliar uma oportunidade.”'),('Em vez de “A IA comprovou”','“A análise automática identificou um sinal que precisa de revisão.”'),('Vocabulário útil','Fonte, contexto, comparar, esclarecer, confirmar, documento, hipótese, revisão. Evitar culpado, desmascarar, garantido e suspeitas sem base.')])
page('AÇÕES','Cada CTA explica\no próximo passo.','O texto do botão descreve uma ação real, com resultado previsível.', [('Entrada','Começar meu Raio-X. Explicar quais informações e documentos serão solicitados.'),('Durante a análise','Ver fontes. Adicionar documento. Entender a comparação.'),('Colaboração','Convidar moradores. Explicar o que o convidado poderá acessar antes de enviar.'),('Módulo adicional','Conhecer a análise. Mostrar escopo, requisitos e preço quando definido, sem resultados fictícios atrás de bloqueios.')])
page('IDENTIDADE','Um olhar atento.\nUma assinatura consistente.','O ninja representa observação, preparo e precisão. O símbolo não precisa de armas, personagens ou efeitos para cumprir esse papel.',kind='divider')
page('NOME','Condo Ninja','C e N maiúsculos, com um espaço entre as palavras. Goldman Regular 400 no wordmark.', [('Em texto','A marca é Condo Ninja. O domínio pretendido é condo.ninja.'),('Em arquivos','Usar nomes técnicos com hífens: condo-ninja. Isso não muda a grafia pública.'),('Em aplicações','Não juntar palavras, alterar o nome ou transformar letras em caixa alta como padrão do logo.')],kind='wordmark')
page('SÍMBOLO','Preservar o olhar.','A silhueta facetada, a máscara e os olhos são os elementos de reconhecimento.', [('Fonte visual','Os dois rasters de referência permanecem em 13_Reference_Assets.'),('Vetor recebido','O pacote V1 contém uma reconstrução. V2 mantém seus caminhos sem redesenho e identifica sua origem.'),('Fidelidade','A reconstrução tem diferenças visíveis de facetas e gradientes frente ao raster de referência. Não é apresentada como equivalência geométrica certificada.')],kind='symbol')
page('CONSTRUÇÃO','Um arquivo mestre.\nNenhuma reconstrução casual.','Usar os arquivos fornecidos, sem remontar o símbolo com formas aproximadas.', [('Elementos invariáveis','Proporção, direção do olhar, máscara, eixo central e contorno externo.'),('Adaptação permitida','Escolher a versão full color, monocromática ou simplificada prevista no pacote.'),('Exportação','Validar olhos, gradientes, recortes e transparência em cada formato. Uma imagem que parece correta no SVG pode falhar ao virar PDF.')],kind='symbol')
page('WORDMARK','Goldman Regular.\nPeso 400.','O nome da marca mantém a personalidade original da Goldman. A interface usa outra hierarquia.', [('Construção','Sem bold artificial, contorno, distorção horizontal, bevel ou glow.'),('Portabilidade','Preferir SVG em curvas para fornecedores. O arquivo editável com texto exige Goldman Regular instalada.'),('Implementação','font-family: "Condo Goldman", sans-serif; font-weight: 400; font-synthesis: none;')],kind='wordmark')
page('LOCKUPS','Uma assinatura\npara cada proporção.','Horizontal como padrão. Vertical para espaços estreitos ou quase quadrados. Símbolo isolado quando a marca já está identificada.', [('Horizontal','Headers, rodapés, documentos, e-mails e apresentações.'),('Vertical','Capas e aplicações com área de marca concentrada.'),('Wordmark isolado','Somente quando o contexto já identifica a marca. Não acrescentar outro símbolo ao nome.')],kind='lockups')
page('PROTEÇÃO','O espaço também\nfaz parte da marca.','x = 1/4 da largura visível do símbolo. Reservar no mínimo x ao redor do conjunto.', [('Medição','Medir sobre a área visual, sem contar margens transparentes do arquivo.'),('Contexto denso','Aumentar o respiro quando houver muitos elementos ou parceiro de marca.'),('Co-branding','Separar assinaturas por pelo menos 2x. Identificar “dados fornecidos por” quando o parceiro é uma fonte, sem sugerir controle da análise.')],kind='clearspace')
page('ESCALA','Reconhecível\nmesmo quando pequeno.','A legibilidade depende do tamanho real, do fundo e da densidade da tela.', [('16–24 px','Usar o símbolo simplificado. Conferir os olhos a 100% e não ampliar para substituir o principal.'),('32 px ou mais','Usar full color quando os detalhes continuarem legíveis.'),('Lockup','Referência inicial: 120 px no digital e 28 mm na impressão. Aumentar quando o suporte ou a leitura exigir.'),('App e avatar','Preservar área segura. As versões quadradas são próprias para recortes de plataforma.')],kind='sizes')
page('FUNDOS','Escolher a versão\nantes de aplicar.','Manter contraste e preservar a identidade dos componentes.', [('Fundo escuro','Símbolo full color e wordmark branco.'),('Fundo claro','Símbolo full color e wordmark Ink 950.'),('Uma tinta','Usar o mestre monocromático apropriado, sem converter o gradiente automaticamente.'),('Uso incorreto','Não esticar, inclinar, recolorir, esconder olhos, aplicar sombra de efeito ou reduzir até perder leitura.')],kind='lockups')
page('CORES','Ink sustenta.\nSignal destaca.','A marca combina profundidade escura com azul de sinal. Paper cria espaço para documentos e leitura prolongada.', [('Ink 950 / #050B1A','Base institucional e superfícies escuras.'),('Signal 500 / #5AC8FF','Acento principal sobre Ink. Usar texto Ink em botões claros.'),('Paper 50 / #FAFBFD','Base de leitura e documentação.'),('Signal 700 / #1B6BFF','Ação primária sobre superfície clara, com texto branco.')],kind='palette')
page('PALETA ESTENDIDA','Profundidade\ncom funções claras.','As escalas completas permanecem nos tokens. Não escolher tons apenas por proximidade visual.', [('Ink','950, 900 e 800: fundos. 600 e 500: texto em superfícies claras. 300 e 200: texto secundário em fundos escuros.'),('Signal','500: assinatura e ação no tema escuro. 700: botão no tema claro. 800: link e foco no tema claro.'),('Gradientes','Restritos ao símbolo e a campos gráficos de marca. Gráficos quantitativos usam cores estáveis.'),('Proporção','Uma cor de destaque por hierarquia. Dar espaço ao conteúdo e evitar preencher cada componente de azul.')],kind='palette')
page('STATUS','Cor acompanha\num significado escrito.','As cores funcionais são subordinadas à identidade. Um estado precisa continuar claro sem percepção de cor.', [('Concluído','Check e rótulo. Verde indica uma etapa concluída, sem declarar boa governança.'),('Atenção','Triângulo, motivo e ação. Âmbar indica revisão necessária.'),('Erro','Mensagem do que falhou e como corrigir. Coral não indica culpa.'),('Verificado','Identificar o objeto e o responsável pela verificação. Não confundir documento conferido com conclusão validada.')],kind='status')
page('ACESSIBILIDADE','O par de cores\né a unidade de decisão.','V2 fornece pares semânticos próprios para temas claro e escuro, com contraste calculado.', [('Texto comum','Exigir pelo menos 4,5:1. Não arredondar um resultado abaixo do limite para aprová-lo.'),('Controles e foco','Borda funcional e indicador de foco precisam de contraste suficiente com a superfície adjacente.'),('Erros de V1 corrigidos','Um único token de foco azul claro falha em fundo claro. V2 usa Signal 800 no claro e Signal 500 no escuro.'),('Auditoria','Consultar 03_Color/contrast-audit.json. A aprovação dos pares não substitui a avaliação da interface completa.')],kind='contrast')
page('TIPOGRAFIA','Três funções.\nUma hierarquia.','A marca, a leitura e os dados exigem ritmos diferentes.', [('Goldman Regular 400','Assinatura. Usar apenas no wordmark e em pequenas expressões de marca.'),('Geist Sans 400 / 500 / 600','Conteúdo, títulos, interface e comunicação.'),('Geist Mono 400 / 500','Valores, identificadores, metadados e trechos técnicos. Números tabulares ajudam a comparação.'),('Licenças','Conservar os avisos OFL junto às fontes. Conferir os textos de licença antes de redistribuir um subconjunto.')],kind='type')
page('ESCALA TIPOGRÁFICA','Leitura antes\ndo efeito tipográfico.','No digital, corpo de 16–18 px e entrelinha de 1,5. Títulos grandes devem quebrar sem comprimir o conteúdo.', [('Display','48–88 px, entrelinha de 1,02–1,1. Reservado à abertura.'),('Títulos','H1 40–56 px. H2 30–40 px. H3 22–26 px.'),('Interface','14–16 px em labels e controles. Evitar texto essencial abaixo de 14 px.'),('Refluxo','Testar 320 px e ampliação de texto. Quebrar palavras longas e reorganizar colunas, em vez de esconder overflow.')],kind='type')
page('ICONOGRAFIA','Objetos reconhecíveis.\nTraço preciso.','A família recebida contém 17 ícones funcionais em uma grade de 24 px.', [('Construção','Traço de 1,8 px, terminais controlados e curvas econômicas. Não usar o símbolo como ícone de todas as funções.'),('Família','Financeiro, contratos, fornecedores, elevadores, manutenção, obras, água, energia, documentos e governança.'),('Continuidade','Jurídico, segurança, evidências, benchmark, investigação, comunidade e mobilização.'),('Acessibilidade','Ícone decorativo recebe alt vazio. Ação sem texto precisa de nome acessível. Em estados relevantes, sempre incluir rótulo visível.')],kind='icons')
page('SISTEMA GRÁFICO','A informação ganha\num campo de evidência.','O elemento proprietário da V2 é a relação visível entre afirmação, fonte e limite.', [('Faceta','Concentra atenção em uma área, com formas derivadas do símbolo.'),('Campo de evidência','Uma afirmação acompanhada por origem, período e situação da revisão.'),('Linha de relação','Conecta dois elementos com significado. Evitar redes decorativas sem conteúdo.'),('Foco','Um destaque por composição. Textura permanece subordinada à legibilidade.')])
page('GRID E COMPOSIÇÃO','Ordem que deixa\no conteúdo respirar.','Alinhamentos previsíveis reduzem esforço de leitura.', [('Desktop','12 colunas, gutter de 24–32 px e largura de conteúdo limitada.'),('Mobile','4 colunas, gutter de 16 px e controles com área de toque mínima de 44 px.'),('Ritmo','Usar a escala de 4 px. Agrupar elementos relacionados e separar blocos com funções diferentes.'),('Editorial','Alternar abertura expressiva e páginas de referência. Evitar repetir a mesma grade de cards em todo o material.')])
page('IMAGEM','Pessoas reais.\nContexto respeitado.','Fotografia deve mostrar a vida compartilhada no condomínio e a atenção às decisões cotidianas.', [('Moradores','Participação natural, diversidade de idades e papéis. Evitar poses de executivos ou cenas de confronto.'),('Edifícios','Arquitetura residencial, manutenção e espaços comuns. Não associar uma imagem real a um achado fictício.'),('Documentos','Anonimizar dados e preservar a legibilidade do trecho que interessa.'),('Ilustração','Facetas e relações entre informações. Personagens só em campanha específica, sem armas, infantilização ou estereótipos.')])
page('DADOS','Todo número precisa\nde uma pergunta e uma fonte.','A visualização explica uma comparação. Não serve apenas como textura tecnológica.', [('Unidade e período','Identificar valores e datas junto do gráfico. Eixo de barras inicia em zero.'),('Linha e faixa','Distinguir observação e referência com rótulos, marcas e estilos além da cor.'),('Ausência','Usar traço e explicação. Nunca converter valor ausente em zero.'),('Conclusão','Uma diferença numérica não identifica causa. Mostrar a lacuna que limita a interpretação.')],kind='chart')
page('BENCHMARK','20% acima de qual base?','Demonstração fictícia: junho custa R$ 1.800 por elevador/mês. O limite superior ilustrativo é R$ 1.500.', [('Cálculo','(1.800 / 1.500 - 1) × 100 = 20%. Comparação contra o limite superior, não contra a média.'),('Escopo','Manutenção preventiva, sem peças ou modernização. Jan–jun de 2026. Amostra sintética de 12 observações.'),('Limitação','Aditivo de escopo ausente. Os números não demonstram sobrepreço, economia recuperável ou irregularidade.'),('Próximo passo','Solicitar o aditivo e confirmar peças, plantões e escopo antes de comparar.')],kind='chart')
page('CONFIANÇA','Explicar a qualidade\nda evidência.','Um percentual como “78%” sugere precisão que a metodologia pode não sustentar. V2 usa uma descrição acompanhada de motivo.', [('Limitada','Há lacunas relevantes ou comparabilidade insuficiente. Mostrar exatamente qual é a lacuna.'),('Contextualizada','Fontes e escopo permitem uma comparação útil, ainda sujeita às limitações indicadas.'),('Revisada','Uma pessoa responsável revisou a afirmação e registrou data, escopo e justificativa.'),('Dimensões separadas','Completude documental, comparabilidade e revisão não são a mesma coisa. Não gerar uma nota geral sem método validado.')])
page('PRODUTO','Um achado completo\ncabe numa leitura.','A interface organiza o contexto antes de pedir uma decisão.', [('1 / Contexto','Condomínio, período e indicação clara quando os dados são de demonstração.'),('2 / Achado','Uma afirmação proporcional ao que a evidência sustenta.'),('3 / Base','Gráfico, fonte, método, documentos faltantes e motivo do nível de confiança.'),('4 / Ação','Próxima pergunta ou documento necessário. O microsite V2 inclui uma demonstração navegável dessa estrutura.')])
page('ESTADOS','O que aconteceu\ne o que fazer agora.','Estado comercial, estado de processamento e qualidade da evidência são eixos diferentes.', [('Processamento','Recebido, em análise, concluído ou falhou. Prazo estimado só quando conhecido.'),('Documento faltante','Nome do documento, impacto da ausência e como adicioná-lo.'),('Dado indisponível','Motivo e possibilidade de obter o dado. Não desenhar um gráfico vazio com valores fictícios.'),('Módulo adicional','Benefício, escopo, requisitos e ação comercial. Sem achados borrados, urgência fabricada ou selo comprado.')],kind='status')
page('MOBILE','A evidência acompanha\na tela pequena.','A versão móvel preserva a mesma ordem de leitura, com menos elementos simultâneos.', [('Uma coluna','Contexto, achado, gráfico, fonte e próximo passo.'),('Gráfico legível','Rótulos resumidos, valores acessíveis em tabela e espaço para toque.'),('Ações','Controles de pelo menos 44 px, foco visível e nome claro.'),('Sem cortes','O conteúdo deve refluir. Tabelas extensas podem ter região própria de rolagem, identificada e acessível.')])
page('MOBILIZAÇÃO','Convidar para\nmelhorar a informação.','Uma comunidade útil começa com uma pergunta compartilhada e um objetivo compreensível.', [('Convite','“Estamos reunindo os documentos para entender melhor as despesas. Você pode colaborar.”'),('Antes de compartilhar','Mostrar quem acessará o quê. O preview público nunca inclui moradores, unidades, valores privados ou acusações.'),('Colaboração','Solicitar o documento necessário, explicar sua finalidade e registrar sua origem.'),('Coordenação','Organizar perguntas para a próxima conversa ou assembleia, respeitando permissões e responsabilidades.')])
page('SELO DE GOVERNANÇA','Uma arquitetura\nque ainda exige método.','Os níveis 0–3 são conceitos de interface. Não são certificações emitidas.', [('Nível 0','Base em formação. Estado inicial, nunca certificado.'),('Níveis 1–3','Documentado, Verificável e Referência são nomes provisórios. Critérios e limiares ainda precisam de validação.'),('Em todos os protótipos','Mostrar “CONCEITO / NÃO CERTIFICA”. Usar o mesmo azul e distinguir nível por número e texto.'),('Independência','Pacote comercial, acesso a módulos e nível de governança permanecem sistemas separados.')],kind='seals')
page('VALIDAÇÃO DO SELO','Um selo só vale\ncom escopo verificável.','A publicação futura precisa permitir entender e contestar o que foi avaliado.', [('Campos obrigatórios','Identificador, condomínio, escopo, data da avaliação, validade, versão do método e responsável.'),('Ciclo de vida','Proposto, em revisão, emitido, vencido, suspenso ou revogado.'),('Consulta pública','Exibir apenas informações autorizadas. O detalhe documental continua sujeito a controle de acesso.'),('Antes de lançar','Definir evidências, pesos, critérios de revisão, correção e contestação. Até lá, manter os visuais como conceitos.')])
page('MOVIMENTO','Uma mudança\nque ajuda a perceber.','Motion orienta atenção e confirma uma transição de estado.', [('Interação','120–180 ms para feedback. Não atrasar a ação.'),('Revelação','280–480 ms, easing cubic-bezier(.2,.8,.2,1). Evitar deslocamentos longos.'),('Scan','Uma execução iniciada pelo usuário, até 1.200 ms. Não simular processamento de dados.'),('Redução de movimento','Trocar animação por estado estático equivalente. Não esconder conteúdo antes do JavaScript ou depender de animação para entender.')])
page('SOCIAL','Uma pergunta útil\npor peça.','O sistema social aproxima a marca das decisões do cotidiano.', [('Instagram','1080 × 1080 para uma ideia. Carrossel 1080 × 1350 para desenvolver uma pergunta em etapas.'),('Story','1080 × 1920. Preservar áreas superiores e inferiores para controles da plataforma.'),('LinkedIn','1200 × 627. Evidência e contexto com linguagem clara, sem transformar uma hipótese em manchete.'),('Regra editorial','Títulos legíveis no celular. Um próximo passo. Dados de exemplo marcados como fictícios.')],kind='applications')
page('CARROSSEL','Uma narrativa\nque termina em ação.','Cinco telas ajudam o morador a comparar um contrato com responsabilidade.', [('01 / A pergunta','Este contrato está caro?'),('02 / O escopo','O que o serviço inclui e exclui?'),('03 / A comparação','Qual unidade, período e região estão sendo comparados?'),('04 e 05 / A ação','O que ainda falta? Solicite o documento e formule a pergunta com contexto.')],kind='applications')
page('DOCUMENTOS','Uma leitura estável\npara registrar decisões.','O relatório HTML é a experiência principal. O PDF registra uma versão datada.', [('Capa A4','Nome do relatório, período, escopo, versão e identificação do destinatário quando apropriado.'),('Corpo','Resumo, achado, fontes, limitações, recomendações e histórico de mudanças.'),('Impressão','A versão deste livro para impressão usa papel claro e formato A4 horizontal. É RGB, adequada a impressão de escritório.'),('Gráfica profissional','Conversão CMYK, perfil ICC, sangria e prova de cor dependem do fornecedor. O PDF não é apresentado como PDF/X certificado.')],kind='report')
page('E-MAIL E NEWSLETTER','O assunto informa.\nO conteúdo orienta.','O e-mail deve permitir entender a atualização sem expor o conteúdo privado da análise.', [('Assunto','“Seu Raio-X recebeu novos documentos”. Evitar alerta acusatório ou informação sensível.'),('Corpo','Explicar o que mudou, o que pode ser visto e qual é o próximo passo.'),('Assinatura','Nome, função, Condo Ninja e canal institucional. Sem slogan concorrente.'),('Compatibilidade','Usar HTML simples com fallback de fonte. Para wordmark em imagem, fornecer texto alternativo. Não depender de fontes web no cliente de e-mail.')])
page('APRESENTAÇÕES','Uma ideia central\npor lâmina.','O template 16:9 recebido permanece disponível e editável. A V2 acrescenta o livro como fonte editorial e exemplos de evidência com contexto.', [('Abertura','Nome da análise, público, período e uma ideia principal.'),('Achado','Dado, referência, limitação e próximo passo em ordem.'),('Discussão','Perguntas a confirmar, documentos necessários e responsáveis quando definidos.'),('Encerramento','Decisão pendente ou ação combinada. Nunca usar o selo como prova comercial de qualidade.')])
page('MICROSITE','A marca demonstrada\nem funcionamento.','O microsite V2 apresenta o conceito e permite explorar decisões de identidade e produto.', [('Identidade','Comparação de fundos do logo, amostras de cor com cópia e hierarquia tipográfica.'),('Evidência','Gráfico com eixos, faixa comparável, tabela acessível, fontes e lacunas em dados explicitamente fictícios.'),('Acessibilidade','HTML semântico, navegação por teclado, foco, menu móvel, redução de movimento e refluxo.'),('Entrega','Arquivos modulares e standalone. A versão standalone incorpora também os arquivos associados aos downloads.')])
page('TOKENS','Um nome semântico\npara cada função.','A cor primitiva descreve o tom. O token semântico descreve o papel no componente.', [('Primitivos','Ink, Signal e Paper preservam a paleta estabelecida.'),('Temas','background, surface, text, muted, action, onAction, focus e estados possuem valores próprios.'),('Componentes','Área de toque, espessura de foco, entrelinha e largura de leitura formalizam regras de uso.'),('Consistência','JSON é a fonte. CSS e arquivos de integração são gerados a partir dele. Não se declara compatibilidade DTCG sem formato tipado e validação.')])
page('IMPLEMENTAÇÃO','Integração gradual\nno produto existente.','O pacote V2 é independente e não altera a aplicação Next.js nem a publicação atual.', [('Primeiro','Importar fontes e variables.css em um ambiente de revisão. Conferir caminhos e licenças.'),('Depois','Substituir cores diretas por tokens semânticos nos componentes. Aplicar data-theme.'),('Compatibilidade','A configuração Tailwind v3 usa ESM. A V2 também inclui mapeamento @theme para v4, sem exigir migração.'),('Revisão','Verificar foco, contraste, estados de erro e ausência de dados em fluxos reais antes de adotar.')])
page('GOVERNANÇA EDITORIAL','Uma conclusão\nprecisa ter responsável.','Regras propostas para operar a marca com rastreabilidade.', [('Autor','Registra fonte, período, método e limitação.'),('Revisor','Avalia a afirmação, a comparabilidade e explicações alternativas.'),('Publicação','Identifica versão, data e estado da revisão. Evita dados pessoais desnecessários.'),('Correção','Preserva histórico, informa o que mudou e reavalia conclusões afetadas. Atribuições precisam ser formalizadas pela equipe.')])
page('CHECKLIST','Antes de usar.','Verificar a aplicação completa, além dos arquivos isolados.', [('Marca','Condo Ninja, Goldman Regular 400, proporções e olhos preservados.'),('Informação','Fonte, período, unidade, limites e dados fictícios identificados.'),('Experiência','Foco visível, teclado, contraste, tamanho de toque, mobile e movimento reduzido.'),('Entrega','Assets existentes, links válidos, licenças incluídas, índice e checksums atualizados.')])
page('ARQUIVOS','Uma entrega\nque se pode rastrear.','O índice relaciona caminho, tamanho, hash e origem de cada arquivo.', [('Preservado','Logos, fontes e materiais V1 mantidos recebem identificação de origem no inventário.'),('Evoluído','Brand Book, microsite, tokens, dados, selos, templates e especificações recebem nova revisão.'),('Editável','Fontes JSON, Python, SVG, HTML, CSS e JavaScript acompanham o pacote.'),('Como começar','Abrir START-HERE.html. Consultar 00_Review/REVIEW-V1.md para entender as decisões.')])
page('DECISÕES ABERTAS','Evoluir quando\na evidência permitir.','A V2 especifica o sistema sem inventar uma metodologia operacional que ainda não existe.', [('Símbolo','Aprovar a equivalência do vetor recebido frente ao raster antes de nomeá-lo master definitivo.'),('Governança','Validar critérios, pesos, validade e processo de contestação do selo.'),('Benchmark','Definir amostra, recorte, atualização, comparabilidade e regras por categoria.'),('Produto','Confirmar módulos disponíveis, revisão humana, preços e condições. Protótipos não provam capacidade implementada.')])
page('FECHAMENTO','A informação só ajuda\nquando se pode entendê-la.','Condo Ninja\nClareza para quem paga condomínio.\nSistema de marca 2.0',kind='closing')
dump('01_Brand_Book/source/book-content.json',pages)
print('Wrote',len(pages),'editorial pages, tokens, contrast audit and synthetic dataset.')
